### ISSUE TITLE
Returning a mockfile.file

### ISSUE THREAD

**Issue by simmel** [seletskiy/go-mock-file#1]
I'm trying to use mockfile to mock a function which returns a os.File, see https://github.com/simmel/oath-ssh-command/blob/57d83017c92d82a11cb8df435274cc55622816dd/main_test.go#L69

I've figured out that it can't work since the mockfile file type isn't exported and things blow up pretty bad if I try to make it exported.

Any idea how to solve my problem? Thanks for an awesome lib!

**Comment by seletskiy** [comment]
Try to declare interface with methods you expect to use, like this one:

```
type file interface {
    io.Closer
    io.Writer
    io.Reader
    io.ReaderAt
    io.Seeker
    Stat() (os.FileInfo, error)
    Truncate(size int64) error
}
```

See usage at: https://github.com/seletskiy/go-embed-fs/blob/master/embedfs.go#L70-85

Mock file used in tests: https://github.com/seletskiy/go-embed-fs/blob/master/embedfs_test.go

See, how mockfile instance used as test container on line 14 in test case.

**Comment by simmel** [comment]
Thanks, that worked!

Maybe you could an example like this to the README? I'm too new to really know what I'm doing, both in Go and with mocking and testing = D
